import styles from "../style";
import northernlights from '../assets/northernlights.jpg';
import { socialMedia } from "../constants";

const Home = () => {
  return (
    <section id="home" style={{ backgroundImage: `url(${northernlights})`, backgroundSize: 'cover', backgroundPosition: 'center' }} className={`${styles.paddingY} h-screen flex flex-col justify-center items-center`}>
      <div className={`${styles.boxWidth} flex flex-col justify-center items-center mt-[-50px]`}>

        <div className="flex flex-col justify-center items-center w-full">
          <h1 className="font-poppins font-semibold text-[52px] text-white leading-[75px] text-center sm:text-[72px] sm:leading-[100.8px]">
            <span className="text-white">Saket Upperla</span>{" "}
          </h1>
        </div>

        <p className="text-white mt-5 text-center max-w-[470px] text-med md:text-lg lg:text-xl">
          Computer Science Student at The University of Texas at Austin
        </p>

        <div className="flex justify-center items-center w-full mt-5">
          {socialMedia.map((social, index) => (
            <img
              key={social.id}
              src={social.icon}
              alt={social.id}
              className={`w-[40px] h-[40px] object-contain cursor-pointer ${index !== socialMedia.length - 1 ? "mr-10" : "mr-0"}`}
              onClick={() => window.open(social.link)}
            />
          ))}
        </div>

        <p className="text-white mt-5 text-center max-w-[470px] text-med md:text-lg lg:text-xl">
          background pic generated by Saket Upperla
        </p>
      </div>
    </section>
  );
};

export default Home;